### PR TITLE
None interactive openssl cert generation

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
This is an alternative setup to #11 which still serves the Jupyter notebook over HTTPS but does not require to user to provide the certificate details.

**Comment by scollis** [comment]
Cool.. I am working on a branch that adds a little.. I will merge yours 
first, there should be no conflicts as I am only working on deps

**Comment by jjhelmus** [comment]
Either #11 or this PR should be selected, not both.

**Comment by scollis** [comment]
I'll have to roll back #11..

I assume you think #12 is superior?

**Comment by jjhelmus** [comment]
I think #11 will cause less headaches at the course but this PR is more secure but will be harder to get working on some browsers.

See discussion in #10

**Comment by scollis** [comment]
We can create a second config file which mirrors #11 that we can fall 
back on.

I favor https as it is DoE Policy that all sites be HTTPS, although 
strictly this is not a DoE site..

**Pull request merged**
