### PR TITLE
ENH: Add examples for Siphon and MetPy

### PR DESCRIPTION
**Pull request by dopplershift**
This covers surface data and station plots, as well as getting data from
the thredds radar server and plotting using pyart.

### CODE REVIEW

**Comment by jjhelmus** [comment]
@dopplershift 

I tested out these two notebooks on an EC2 instance and am getting the following error from the "Siphon Radar Server" notebook when executing the first cell:

``` Python
from siphon.catalog import TDSCatalog
cat = TDSCatalog('http://thredds-aws.unidata.ucar.edu/thredds/radarServer/catalog.xml')
list(cat.catalog_refs)
```

```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-2-a108379447a5> in <module>()
      1 from siphon.catalog import TDSCatalog
----> 2 cat = TDSCatalog('http://thredds-aws.unidata.ucar.edu/thredds/radarServer/catalog.xml')
      3 list(cat.catalog_refs)

/home/ubuntu/miniconda3/envs/ams-workshop/lib/python3.5/site-packages/siphon/catalog.py in __init__(self, catalog_url)
     63         # get catalog.xml file
     64         resp = session.get(self.catalog_url)
---> 65         resp.raise_for_status()
     66 
     67         # If we were given an HTML link, warn about it and try to fix to xml

/home/ubuntu/miniconda3/envs/ams-workshop/lib/python3.5/site-packages/requests/models.py in raise_for_status(self)
    891 
    892         if http_error_msg:
--> 893             raise HTTPError(http_error_msg, response=self)
    894 
    895     def close(self):

HTTPError: 403 Client Error: Forbidden for url: http://thredds-aws.unidata.ucar.edu/thredds/radarServer/catalog.xml
```

Is access to the thredds-aws catalog locked to a set of IPs or domains?

**Comment by dopplershift** [comment]
It is currently--I'll turn it off for the workshop, or possibly stand up a new one just for the workshop.

**Comment by scollis** [comment]
Cool..

Could you open it up to *.anl.gov so I can experiment?

I wonder if I log into Eduroam does it work?

**Comment by dopplershift** [comment]
I *wish* it were as easy as a whitelist. *sigh* Stupid Tomcat.

I'll have something this morning or just after lunch. In the meanwhile, for small experiments, just point to http://thredds.ucar.edu/thredds/radarServer

**Comment by scollis** [comment]
Thanks.. actually if it is just for the radarserver it is  no big deal.

**Comment by dopplershift** [comment]
It's just the THREDDS instance we run in AWS, since we're on the hook for the bandwidth bill.  The s3 bucket itself should be completely wide open.

**Comment by scollis** [comment]
Exactly.. for the final demo I will use Boto..

S3-> Eastcoast AWS is free

**Comment by dopplershift** [comment]
@scollis If you want to try, there's a new server up at:

http://52.90.147.218/thredds/catalog.html

At some point, I'll update the notebook to point to:

http://52.90.147.218/thredds/radarServer/catalog.xml

**Comment by scollis** [comment]
Thanks! BTW have you got a satellite example handy?

**Comment by dopplershift** [comment]
Yeah: 

https://github.com/Unidata/unidata-python-workshop/blob/master/notebooks/GINI%20Satellite%20with%20MetPy%20and%20Siphon.ipynb

Somehow, I think you're working on this same problem I did in Unidata/MetPy#243

image

**Comment by scollis** [comment]
Epic :)

**Comment by dopplershift** [comment]
While the map is cool, it refers to the type of issue in the Agile methodology. :grin:

**Pull request merged**
